//this source code was auto-generated by tolua#, do not modify it
using System;
using System.Collections.Generic;
using LuaInterface;

public static class DelegateFactory
{
	public delegate Delegate DelegateValue(LuaFunction func);
	public static Dictionary<Type, DelegateValue> dict = new Dictionary<Type, DelegateValue>();

	static DelegateFactory()
	{
		Register();
	}

	[NoToLuaAttribute]
	public static void Register()
	{
		dict.Clear();
		dict.Add(typeof(System.Action), System_Action);
		dict.Add(typeof(UnityEngine.Events.UnityAction), UnityEngine_Events_UnityAction);
		dict.Add(typeof(UnityEngine.Application.LogCallback), UnityEngine_Application_LogCallback);
		dict.Add(typeof(UnityEngine.Application.AdvertisingIdentifierCallback), UnityEngine_Application_AdvertisingIdentifierCallback);
		dict.Add(typeof(UnityEngine.Camera.CameraCallback), UnityEngine_Camera_CameraCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMReaderCallback), UnityEngine_AudioClip_PCMReaderCallback);
		dict.Add(typeof(UnityEngine.AudioClip.PCMSetPositionCallback), UnityEngine_AudioClip_PCMSetPositionCallback);
		dict.Add(typeof(UnityEngine.RectTransform.ReapplyDrivenProperties), UnityEngine_RectTransform_ReapplyDrivenProperties);
		dict.Add(typeof(System.Action<NotiData>), System_Action_NotiData);
		dict.Add(typeof(System.Action<object>), System_Action_object);
		dict.Add(typeof(System.Action<float>), System_Action_float);
		dict.Add(typeof(System.Action<float,float>), System_Action_float_float);
		dict.Add(typeof(System.Action<UnityEngine.Color>), System_Action_UnityEngine_Color);
		dict.Add(typeof(System.Action<UnityEngine.Vector2>), System_Action_UnityEngine_Vector2);
		dict.Add(typeof(System.Action<UnityEngine.Vector3>), System_Action_UnityEngine_Vector3);
		dict.Add(typeof(System.Action<float,object>), System_Action_float_object);
		dict.Add(typeof(System.Action<LTEvent>), System_Action_LTEvent);
		dict.Add(typeof(System.Action<UnityEngine.Vector3,object>), System_Action_UnityEngine_Vector3_object);
		dict.Add(typeof(EventDelegate.Callback), EventDelegate_Callback);
		dict.Add(typeof(UIGrid.OnReposition), UIGrid_OnReposition);
		dict.Add(typeof(System.Comparison<UnityEngine.Transform>), System_Comparison_UnityEngine_Transform);
		dict.Add(typeof(UISpriteAnimation.AnimationCallback), UISpriteAnimation_AnimationCallback);
		dict.Add(typeof(UIEventListener.VoidDelegate), UIEventListener_VoidDelegate);
		dict.Add(typeof(UIEventListener.BoolDelegate), UIEventListener_BoolDelegate);
		dict.Add(typeof(UIEventListener.FloatDelegate), UIEventListener_FloatDelegate);
		dict.Add(typeof(UIEventListener.VectorDelegate), UIEventListener_VectorDelegate);
		dict.Add(typeof(UIEventListener.ObjectDelegate), UIEventListener_ObjectDelegate);
		dict.Add(typeof(UIEventListener.KeyCodeDelegate), UIEventListener_KeyCodeDelegate);
		dict.Add(typeof(UICamera.GetKeyStateFunc), UICamera_GetKeyStateFunc);
		dict.Add(typeof(UICamera.GetAxisFunc), UICamera_GetAxisFunc);
		dict.Add(typeof(UICamera.GetAnyKeyFunc), UICamera_GetAnyKeyFunc);
		dict.Add(typeof(UICamera.OnScreenResize), UICamera_OnScreenResize);
		dict.Add(typeof(UICamera.OnCustomInput), UICamera_OnCustomInput);
		dict.Add(typeof(UICamera.OnSchemeChange), UICamera_OnSchemeChange);
		dict.Add(typeof(UICamera.VoidDelegate), UICamera_VoidDelegate);
		dict.Add(typeof(UICamera.BoolDelegate), UICamera_BoolDelegate);
		dict.Add(typeof(UICamera.FloatDelegate), UICamera_FloatDelegate);
		dict.Add(typeof(UICamera.VectorDelegate), UICamera_VectorDelegate);
		dict.Add(typeof(UICamera.ObjectDelegate), UICamera_ObjectDelegate);
		dict.Add(typeof(UICamera.KeyCodeDelegate), UICamera_KeyCodeDelegate);
		dict.Add(typeof(UICamera.MoveDelegate), UICamera_MoveDelegate);
		dict.Add(typeof(UICamera.GetTouchCountCallback), UICamera_GetTouchCountCallback);
		dict.Add(typeof(UICamera.GetTouchCallback), UICamera_GetTouchCallback);
		dict.Add(typeof(UIWidget.OnDimensionsChanged), UIWidget_OnDimensionsChanged);
		dict.Add(typeof(UIWidget.OnPostFillCallback), UIWidget_OnPostFillCallback);
		dict.Add(typeof(UIDrawCall.OnRenderCallback), UIDrawCall_OnRenderCallback);
		dict.Add(typeof(UIWidget.HitCheck), UIWidget_HitCheck);
		dict.Add(typeof(UIPanel.OnGeometryUpdated), UIPanel_OnGeometryUpdated);
		dict.Add(typeof(UIPanel.OnClippingMoved), UIPanel_OnClippingMoved);
	}

    [NoToLuaAttribute]
    public static Delegate CreateDelegate(Type t, LuaFunction func = null)
    {
        DelegateValue create = null;

        if (!dict.TryGetValue(t, out create))
        {
            throw new LuaException(string.Format("Delegate {0} not register", LuaMisc.GetTypeName(t)));            
        }
        
        return create(func);        
    }

    [NoToLuaAttribute]
    public static Delegate RemoveDelegate(Delegate obj, LuaFunction func)
    {
        LuaState state = func.GetLuaState();
        Delegate[] ds = obj.GetInvocationList();

        for (int i = 0; i < ds.Length; i++)
        {
            LuaDelegate ld = ds[i].Target as LuaDelegate;

            if (ld != null && ld.func == func)
            {
                obj = Delegate.Remove(obj, ds[i]);
                state.DelayDispose(ld.func);
                break;
            }
        }

        return obj;
    }

	class System_Action_Event : LuaDelegate
	{
		public System_Action_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate System_Action(LuaFunction func)
	{
		if (func == null)
		{
			System.Action fn = delegate { };
			return fn;
		}

		System.Action d = (new System_Action_Event(func)).Call;
		return d;
	}

	class UnityEngine_Events_UnityAction_Event : LuaDelegate
	{
		public UnityEngine_Events_UnityAction_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UnityEngine_Events_UnityAction(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Events.UnityAction fn = delegate { };
			return fn;
		}

		UnityEngine.Events.UnityAction d = (new UnityEngine_Events_UnityAction_Event(func)).Call;
		return d;
	}

	class UnityEngine_Application_LogCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_LogCallback_Event(LuaFunction func) : base(func) { }

		public void Call(string param0,string param1,UnityEngine.LogType param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_LogCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Application.LogCallback fn = delegate { };
			return fn;
		}

		UnityEngine.Application.LogCallback d = (new UnityEngine_Application_LogCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_Application_AdvertisingIdentifierCallback_Event : LuaDelegate
	{
		public UnityEngine_Application_AdvertisingIdentifierCallback_Event(LuaFunction func) : base(func) { }

		public void Call(string param0,bool param1,string param2)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.Push(param2);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Application_AdvertisingIdentifierCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Application.AdvertisingIdentifierCallback fn = delegate { };
			return fn;
		}

		UnityEngine.Application.AdvertisingIdentifierCallback d = (new UnityEngine_Application_AdvertisingIdentifierCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_Camera_CameraCallback_Event : LuaDelegate
	{
		public UnityEngine_Camera_CameraCallback_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Camera param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_Camera_CameraCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.Camera.CameraCallback fn = delegate { };
			return fn;
		}

		UnityEngine.Camera.CameraCallback d = (new UnityEngine_Camera_CameraCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_AudioClip_PCMReaderCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMReaderCallback_Event(LuaFunction func) : base(func) { }

		public void Call(float[] param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMReaderCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMReaderCallback fn = delegate { };
			return fn;
		}

		UnityEngine.AudioClip.PCMReaderCallback d = (new UnityEngine_AudioClip_PCMReaderCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_AudioClip_PCMSetPositionCallback_Event : LuaDelegate
	{
		public UnityEngine_AudioClip_PCMSetPositionCallback_Event(LuaFunction func) : base(func) { }

		public void Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_AudioClip_PCMSetPositionCallback(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.AudioClip.PCMSetPositionCallback fn = delegate { };
			return fn;
		}

		UnityEngine.AudioClip.PCMSetPositionCallback d = (new UnityEngine_AudioClip_PCMSetPositionCallback_Event(func)).Call;
		return d;
	}

	class UnityEngine_RectTransform_ReapplyDrivenProperties_Event : LuaDelegate
	{
		public UnityEngine_RectTransform_ReapplyDrivenProperties_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.RectTransform param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UnityEngine_RectTransform_ReapplyDrivenProperties(LuaFunction func)
	{
		if (func == null)
		{
			UnityEngine.RectTransform.ReapplyDrivenProperties fn = delegate { };
			return fn;
		}

		UnityEngine.RectTransform.ReapplyDrivenProperties d = (new UnityEngine_RectTransform_ReapplyDrivenProperties_Event(func)).Call;
		return d;
	}

	class System_Action_NotiData_Event : LuaDelegate
	{
		public System_Action_NotiData_Event(LuaFunction func) : base(func) { }

		public void Call(NotiData param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_NotiData(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<NotiData> fn = delegate { };
			return fn;
		}

		System.Action<NotiData> d = (new System_Action_NotiData_Event(func)).Call;
		return d;
	}

	class System_Action_object_Event : LuaDelegate
	{
		public System_Action_object_Event(LuaFunction func) : base(func) { }

		public void Call(object param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_object(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<object> fn = delegate { };
			return fn;
		}

		System.Action<object> d = (new System_Action_object_Event(func)).Call;
		return d;
	}

	class System_Action_float_Event : LuaDelegate
	{
		public System_Action_float_Event(LuaFunction func) : base(func) { }

		public void Call(float param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_float(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<float> fn = delegate { };
			return fn;
		}

		System.Action<float> d = (new System_Action_float_Event(func)).Call;
		return d;
	}

	class System_Action_float_float_Event : LuaDelegate
	{
		public System_Action_float_float_Event(LuaFunction func) : base(func) { }

		public void Call(float param0,float param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_float_float(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<float,float> fn = delegate { };
			return fn;
		}

		System.Action<float,float> d = (new System_Action_float_float_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Color_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Color_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Color param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Color(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Color> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Color> d = (new System_Action_UnityEngine_Color_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Vector2_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Vector2_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Vector2 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Vector2(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Vector2> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Vector2> d = (new System_Action_UnityEngine_Vector2_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Vector3_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Vector3_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Vector3 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Vector3(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Vector3> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Vector3> d = (new System_Action_UnityEngine_Vector3_Event(func)).Call;
		return d;
	}

	class System_Action_float_object_Event : LuaDelegate
	{
		public System_Action_float_object_Event(LuaFunction func) : base(func) { }

		public void Call(float param0,object param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_float_object(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<float,object> fn = delegate { };
			return fn;
		}

		System.Action<float,object> d = (new System_Action_float_object_Event(func)).Call;
		return d;
	}

	class System_Action_LTEvent_Event : LuaDelegate
	{
		public System_Action_LTEvent_Event(LuaFunction func) : base(func) { }

		public void Call(LTEvent param0)
		{
			func.BeginPCall();
			func.PushObject(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_LTEvent(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<LTEvent> fn = delegate { };
			return fn;
		}

		System.Action<LTEvent> d = (new System_Action_LTEvent_Event(func)).Call;
		return d;
	}

	class System_Action_UnityEngine_Vector3_object_Event : LuaDelegate
	{
		public System_Action_UnityEngine_Vector3_object_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Vector3 param0,object param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate System_Action_UnityEngine_Vector3_object(LuaFunction func)
	{
		if (func == null)
		{
			System.Action<UnityEngine.Vector3,object> fn = delegate { };
			return fn;
		}

		System.Action<UnityEngine.Vector3,object> d = (new System_Action_UnityEngine_Vector3_object_Event(func)).Call;
		return d;
	}

	class EventDelegate_Callback_Event : LuaDelegate
	{
		public EventDelegate_Callback_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate EventDelegate_Callback(LuaFunction func)
	{
		if (func == null)
		{
			EventDelegate.Callback fn = delegate { };
			return fn;
		}

		EventDelegate.Callback d = (new EventDelegate_Callback_Event(func)).Call;
		return d;
	}

	class UIGrid_OnReposition_Event : LuaDelegate
	{
		public UIGrid_OnReposition_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UIGrid_OnReposition(LuaFunction func)
	{
		if (func == null)
		{
			UIGrid.OnReposition fn = delegate { };
			return fn;
		}

		UIGrid.OnReposition d = (new UIGrid_OnReposition_Event(func)).Call;
		return d;
	}

	class System_Comparison_UnityEngine_Transform_Event : LuaDelegate
	{
		public System_Comparison_UnityEngine_Transform_Event(LuaFunction func) : base(func) { }

		public int Call(UnityEngine.Transform param0,UnityEngine.Transform param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			int ret = (int)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate System_Comparison_UnityEngine_Transform(LuaFunction func)
	{
		if (func == null)
		{
			System.Comparison<UnityEngine.Transform> fn = delegate { return 0; };
			return fn;
		}

		System.Comparison<UnityEngine.Transform> d = (new System_Comparison_UnityEngine_Transform_Event(func)).Call;
		return d;
	}

	class UISpriteAnimation_AnimationCallback_Event : LuaDelegate
	{
		public UISpriteAnimation_AnimationCallback_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UISpriteAnimation_AnimationCallback(LuaFunction func)
	{
		if (func == null)
		{
			UISpriteAnimation.AnimationCallback fn = delegate { };
			return fn;
		}

		UISpriteAnimation.AnimationCallback d = (new UISpriteAnimation_AnimationCallback_Event(func)).Call;
		return d;
	}

	class UIEventListener_VoidDelegate_Event : LuaDelegate
	{
		public UIEventListener_VoidDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIEventListener_VoidDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UIEventListener.VoidDelegate fn = delegate { };
			return fn;
		}

		UIEventListener.VoidDelegate d = (new UIEventListener_VoidDelegate_Event(func)).Call;
		return d;
	}

	class UIEventListener_BoolDelegate_Event : LuaDelegate
	{
		public UIEventListener_BoolDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,bool param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIEventListener_BoolDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UIEventListener.BoolDelegate fn = delegate { };
			return fn;
		}

		UIEventListener.BoolDelegate d = (new UIEventListener_BoolDelegate_Event(func)).Call;
		return d;
	}

	class UIEventListener_FloatDelegate_Event : LuaDelegate
	{
		public UIEventListener_FloatDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,float param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIEventListener_FloatDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UIEventListener.FloatDelegate fn = delegate { };
			return fn;
		}

		UIEventListener.FloatDelegate d = (new UIEventListener_FloatDelegate_Event(func)).Call;
		return d;
	}

	class UIEventListener_VectorDelegate_Event : LuaDelegate
	{
		public UIEventListener_VectorDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,UnityEngine.Vector2 param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIEventListener_VectorDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UIEventListener.VectorDelegate fn = delegate { };
			return fn;
		}

		UIEventListener.VectorDelegate d = (new UIEventListener_VectorDelegate_Event(func)).Call;
		return d;
	}

	class UIEventListener_ObjectDelegate_Event : LuaDelegate
	{
		public UIEventListener_ObjectDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,UnityEngine.GameObject param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIEventListener_ObjectDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UIEventListener.ObjectDelegate fn = delegate { };
			return fn;
		}

		UIEventListener.ObjectDelegate d = (new UIEventListener_ObjectDelegate_Event(func)).Call;
		return d;
	}

	class UIEventListener_KeyCodeDelegate_Event : LuaDelegate
	{
		public UIEventListener_KeyCodeDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,UnityEngine.KeyCode param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIEventListener_KeyCodeDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UIEventListener.KeyCodeDelegate fn = delegate { };
			return fn;
		}

		UIEventListener.KeyCodeDelegate d = (new UIEventListener_KeyCodeDelegate_Event(func)).Call;
		return d;
	}

	class UICamera_GetKeyStateFunc_Event : LuaDelegate
	{
		public UICamera_GetKeyStateFunc_Event(LuaFunction func) : base(func) { }

		public bool Call(UnityEngine.KeyCode param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UICamera_GetKeyStateFunc(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.GetKeyStateFunc fn = delegate { return false; };
			return fn;
		}

		UICamera.GetKeyStateFunc d = (new UICamera_GetKeyStateFunc_Event(func)).Call;
		return d;
	}

	class UICamera_GetAxisFunc_Event : LuaDelegate
	{
		public UICamera_GetAxisFunc_Event(LuaFunction func) : base(func) { }

		public float Call(string param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			float ret = (float)func.CheckNumber();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UICamera_GetAxisFunc(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.GetAxisFunc fn = delegate { return 0; };
			return fn;
		}

		UICamera.GetAxisFunc d = (new UICamera_GetAxisFunc_Event(func)).Call;
		return d;
	}

	class UICamera_GetAnyKeyFunc_Event : LuaDelegate
	{
		public UICamera_GetAnyKeyFunc_Event(LuaFunction func) : base(func) { }

		public bool Call()
		{
			func.Call();
		bool ret = func.CheckBoolean();
			return ret;
		}
	}

	public static Delegate UICamera_GetAnyKeyFunc(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.GetAnyKeyFunc fn = delegate { return false; };
			return fn;
		}

		UICamera.GetAnyKeyFunc d = (new UICamera_GetAnyKeyFunc_Event(func)).Call;
		return d;
	}

	class UICamera_OnScreenResize_Event : LuaDelegate
	{
		public UICamera_OnScreenResize_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UICamera_OnScreenResize(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.OnScreenResize fn = delegate { };
			return fn;
		}

		UICamera.OnScreenResize d = (new UICamera_OnScreenResize_Event(func)).Call;
		return d;
	}

	class UICamera_OnCustomInput_Event : LuaDelegate
	{
		public UICamera_OnCustomInput_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UICamera_OnCustomInput(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.OnCustomInput fn = delegate { };
			return fn;
		}

		UICamera.OnCustomInput d = (new UICamera_OnCustomInput_Event(func)).Call;
		return d;
	}

	class UICamera_OnSchemeChange_Event : LuaDelegate
	{
		public UICamera_OnSchemeChange_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UICamera_OnSchemeChange(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.OnSchemeChange fn = delegate { };
			return fn;
		}

		UICamera.OnSchemeChange d = (new UICamera_OnSchemeChange_Event(func)).Call;
		return d;
	}

	class UICamera_VoidDelegate_Event : LuaDelegate
	{
		public UICamera_VoidDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UICamera_VoidDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.VoidDelegate fn = delegate { };
			return fn;
		}

		UICamera.VoidDelegate d = (new UICamera_VoidDelegate_Event(func)).Call;
		return d;
	}

	class UICamera_BoolDelegate_Event : LuaDelegate
	{
		public UICamera_BoolDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,bool param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UICamera_BoolDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.BoolDelegate fn = delegate { };
			return fn;
		}

		UICamera.BoolDelegate d = (new UICamera_BoolDelegate_Event(func)).Call;
		return d;
	}

	class UICamera_FloatDelegate_Event : LuaDelegate
	{
		public UICamera_FloatDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,float param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UICamera_FloatDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.FloatDelegate fn = delegate { };
			return fn;
		}

		UICamera.FloatDelegate d = (new UICamera_FloatDelegate_Event(func)).Call;
		return d;
	}

	class UICamera_VectorDelegate_Event : LuaDelegate
	{
		public UICamera_VectorDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,UnityEngine.Vector2 param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UICamera_VectorDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.VectorDelegate fn = delegate { };
			return fn;
		}

		UICamera.VectorDelegate d = (new UICamera_VectorDelegate_Event(func)).Call;
		return d;
	}

	class UICamera_ObjectDelegate_Event : LuaDelegate
	{
		public UICamera_ObjectDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,UnityEngine.GameObject param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UICamera_ObjectDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.ObjectDelegate fn = delegate { };
			return fn;
		}

		UICamera.ObjectDelegate d = (new UICamera_ObjectDelegate_Event(func)).Call;
		return d;
	}

	class UICamera_KeyCodeDelegate_Event : LuaDelegate
	{
		public UICamera_KeyCodeDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.GameObject param0,UnityEngine.KeyCode param1)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UICamera_KeyCodeDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.KeyCodeDelegate fn = delegate { };
			return fn;
		}

		UICamera.KeyCodeDelegate d = (new UICamera_KeyCodeDelegate_Event(func)).Call;
		return d;
	}

	class UICamera_MoveDelegate_Event : LuaDelegate
	{
		public UICamera_MoveDelegate_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Vector2 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UICamera_MoveDelegate(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.MoveDelegate fn = delegate { };
			return fn;
		}

		UICamera.MoveDelegate d = (new UICamera_MoveDelegate_Event(func)).Call;
		return d;
	}

	class UICamera_GetTouchCountCallback_Event : LuaDelegate
	{
		public UICamera_GetTouchCountCallback_Event(LuaFunction func) : base(func) { }

		public int Call()
		{
			func.Call();
		int ret = (int)func.CheckNumber();
			return ret;
		}
	}

	public static Delegate UICamera_GetTouchCountCallback(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.GetTouchCountCallback fn = delegate { return 0; };
			return fn;
		}

		UICamera.GetTouchCountCallback d = (new UICamera_GetTouchCountCallback_Event(func)).Call;
		return d;
	}

	class UICamera_GetTouchCallback_Event : LuaDelegate
	{
		public UICamera_GetTouchCallback_Event(LuaFunction func) : base(func) { }

		public UICamera.Touch Call(int param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			UICamera.Touch ret = (UICamera.Touch)func.CheckObject(typeof(UICamera.Touch));
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UICamera_GetTouchCallback(LuaFunction func)
	{
		if (func == null)
		{
			UICamera.GetTouchCallback fn = delegate { return null; };
			return fn;
		}

		UICamera.GetTouchCallback d = (new UICamera_GetTouchCallback_Event(func)).Call;
		return d;
	}

	class UIWidget_OnDimensionsChanged_Event : LuaDelegate
	{
		public UIWidget_OnDimensionsChanged_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UIWidget_OnDimensionsChanged(LuaFunction func)
	{
		if (func == null)
		{
			UIWidget.OnDimensionsChanged fn = delegate { };
			return fn;
		}

		UIWidget.OnDimensionsChanged d = (new UIWidget_OnDimensionsChanged_Event(func)).Call;
		return d;
	}

	class UIWidget_OnPostFillCallback_Event : LuaDelegate
	{
		public UIWidget_OnPostFillCallback_Event(LuaFunction func) : base(func) { }

		public void Call(UIWidget param0,int param1,BetterList<UnityEngine.Vector3> param2,BetterList<UnityEngine.Vector2> param3,BetterList<UnityEngine.Color32> param4)
		{
			func.BeginPCall();
			func.Push(param0);
			func.Push(param1);
			func.PushObject(param2);
			func.PushObject(param3);
			func.PushObject(param4);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIWidget_OnPostFillCallback(LuaFunction func)
	{
		if (func == null)
		{
			UIWidget.OnPostFillCallback fn = delegate { };
			return fn;
		}

		UIWidget.OnPostFillCallback d = (new UIWidget_OnPostFillCallback_Event(func)).Call;
		return d;
	}

	class UIDrawCall_OnRenderCallback_Event : LuaDelegate
	{
		public UIDrawCall_OnRenderCallback_Event(LuaFunction func) : base(func) { }

		public void Call(UnityEngine.Material param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIDrawCall_OnRenderCallback(LuaFunction func)
	{
		if (func == null)
		{
			UIDrawCall.OnRenderCallback fn = delegate { };
			return fn;
		}

		UIDrawCall.OnRenderCallback d = (new UIDrawCall_OnRenderCallback_Event(func)).Call;
		return d;
	}

	class UIWidget_HitCheck_Event : LuaDelegate
	{
		public UIWidget_HitCheck_Event(LuaFunction func) : base(func) { }

		public bool Call(UnityEngine.Vector3 param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			bool ret = func.CheckBoolean();
			func.EndPCall();
			return ret;
		}
	}

	public static Delegate UIWidget_HitCheck(LuaFunction func)
	{
		if (func == null)
		{
			UIWidget.HitCheck fn = delegate { return false; };
			return fn;
		}

		UIWidget.HitCheck d = (new UIWidget_HitCheck_Event(func)).Call;
		return d;
	}

	class UIPanel_OnGeometryUpdated_Event : LuaDelegate
	{
		public UIPanel_OnGeometryUpdated_Event(LuaFunction func) : base(func) { }

		public void Call()
		{
			func.Call();
		}
	}

	public static Delegate UIPanel_OnGeometryUpdated(LuaFunction func)
	{
		if (func == null)
		{
			UIPanel.OnGeometryUpdated fn = delegate { };
			return fn;
		}

		UIPanel.OnGeometryUpdated d = (new UIPanel_OnGeometryUpdated_Event(func)).Call;
		return d;
	}

	class UIPanel_OnClippingMoved_Event : LuaDelegate
	{
		public UIPanel_OnClippingMoved_Event(LuaFunction func) : base(func) { }

		public void Call(UIPanel param0)
		{
			func.BeginPCall();
			func.Push(param0);
			func.PCall();
			func.EndPCall();
		}
	}

	public static Delegate UIPanel_OnClippingMoved(LuaFunction func)
	{
		if (func == null)
		{
			UIPanel.OnClippingMoved fn = delegate { };
			return fn;
		}

		UIPanel.OnClippingMoved d = (new UIPanel_OnClippingMoved_Event(func)).Call;
		return d;
	}

}

