//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class JJButtonWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(JJButton), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("AddClickCallback", AddClickCallback);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", Lua_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddClickCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			JJButton obj = (JJButton)ToLua.CheckObject(L, 1, typeof(JJButton));
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			object arg1 = ToLua.ToVarObject(L, 3);
			obj.AddClickCallback(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Lua_ToString(IntPtr L)
	{
		object obj = ToLua.ToObject(L, 1);

		if (obj != null)
		{
			LuaDLL.lua_pushstring(L, obj.ToString());
		}
		else
		{
			LuaDLL.lua_pushnil(L);
		}

		return 1;
	}
}

